### ISSUE TITLE
error 500 in pages

### ISSUE THREAD

**Issue by medicamin** [bludit-plugins/snicker#2]
Hi there,
By enabling snicker plugin, I get error 500 on blog pages. But admin area is ok.
digging to logs, I got this:

`Stack trace:
#0 /home/user/public_html/type/bludit/bl-plugins/snicker/plugin.php(801): Session::start()
#1 /home/user/public_html/type/bludit/bl-kernel/helpers/theme.class.php(233): SnickerPlugin->beforeSiteLoad()
#2 /home/user/public_html/type/bludit/bl-kernel/boot/site.php(17): Theme::plugins('beforeSiteLoad')
#3 /home/user/public_html/type/bludit/index.php(42): require('/home/user/...')
#4 {main}`

Bludit ver: 3.15.0
snicker: 0.1.2

**Comment by medicamin** [comment]
I found the solution in [this reply](https://github.com/bludit/bludit/issues/1478#issuecomment-1352463504) from bludit github page:
change line 801 in plugin.php to Session::start('', true);

**Comment by medicamin** [comment]
I found the solution in [this reply](https://github.com/bludit/bludit/issues/1478#issuecomment-1352463504) from bludit github page:
change line 801 in plugin.php to Session::start('', true);
