### ISSUE TITLE
500 error after activating the plugin

### ISSUE THREAD

**Issue by DoCheckor** [bludit-plugins/snicker#3]
Hi!

Running Bludit 3.15.0 

Installed the 0.1.2 version from https://plugins.bludit.com/plugin/snicker

After activating the plugin the webserver returns a 500 on the main page / blog . 

Access to admin is still possible. Deactivating the plugin will let me use the blog again.

Any ideas?

**Comment by DoCheckor** [comment]
PS: The requirements for using snickers (on the github main page) state I must use Bluedit v3.5.0+

Maybe that's why it doesn't work for me ? ;-p

**Comment by DoCheckor** [comment]
This is on IIS server / php 7.2.14

More details from running in debug mode:

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Session::start(), 0 passed in C:\inetpub\wwwroot\bl-plugins\snicker\plugin.php on line 801 and exactly 2 expected in C:\inetpub\wwwroot\bl-kernel\helpers\session.class.php:8 Stack trace: #0 C:\inetpub\wwwroot\bl-plugins\snicker\plugin.php(801): Session::start() #1 C:\inetpub\wwwroot\bl-kernel\helpers\theme.class.php(233): SnickerPlugin->beforeSiteLoad() #2 C:\inetpub\wwwroot\bl-kernel\boot\site.php(17): Theme::plugins('beforeSiteLoad') #3 C:\inetpub\wwwroot\index.php(42): require('C:\\inetpub\\wwwr...') #4 {main} thrown in C:\inetpub\wwwroot\bl-kernel\helpers\session.class.php on line 8

**Comment by dejalavidavolar** [comment]
same error here :c

**Comment by divtechau** [comment]
Also same here :(

**Comment by Mates-K1** [comment]
Try this, it works for me.

https://github.com/bludit/bludit/issues/1478#issuecomment-1352463504
